#!/bin/bash

# Script to patch Capacitor's auto-generated build.gradle files to use Java 17
# This is needed for local development when Java 21 is not available
# Patches all Capacitor-related Gradle files that reference Java 21

# Files to patch
FILES=(
    "android/app/capacitor.build.gradle"
    "node_modules/@capacitor/android/capacitor/build.gradle"
    "android/capacitor-cordova-android-plugins/build.gradle"
)

echo "Patching Capacitor files to use Java 17..."
echo ""

PATCHED_COUNT=0
SKIPPED_COUNT=0

for FILE in "${FILES[@]}"; do
    if [ ! -f "$FILE" ]; then
        echo "⊘ Skipping $FILE (not found)"
        SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
        continue
    fi
    
    # Check if file contains VERSION_21
    if ! grep -q "VERSION_21" "$FILE"; then
        echo "⊘ Skipping $FILE (already patched or no VERSION_21 found)"
        SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
        continue
    fi
    
    # Replace VERSION_21 with VERSION_17 (cross-platform compatible)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' "$FILE"
    else
        # Linux and others
        sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' "$FILE"
    fi
    
    echo "✓ Patched $FILE"
    PATCHED_COUNT=$((PATCHED_COUNT + 1))
done

echo ""
echo "Summary: $PATCHED_COUNT file(s) patched, $SKIPPED_COUNT file(s) skipped"
echo ""
echo "Note: Some files are auto-generated by Capacitor and will be reset when you run 'npx cap sync'"
echo "Re-run this script after syncing if needed for local development with Java 17"
