#!/bin/bash

# Script to patch Capacitor's auto-generated build.gradle to use Java 17
# This is needed for local development when Java 21 is not available
# CI/CD should use Java 21 as configured in the workflow

CAPACITOR_BUILD_GRADLE="android/app/capacitor.build.gradle"

if [ ! -f "$CAPACITOR_BUILD_GRADLE" ]; then
    echo "Error: $CAPACITOR_BUILD_GRADLE not found"
    echo "Please run 'npm run android:init' or 'npx cap add android' first"
    exit 1
fi

echo "Patching $CAPACITOR_BUILD_GRADLE to use Java 17..."

# Replace VERSION_21 with VERSION_17
sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' "$CAPACITOR_BUILD_GRADLE"

echo "✓ Patched successfully"
echo ""
echo "Note: This file is auto-generated by Capacitor and will be reset when you run 'npx cap sync'"
echo "Re-run this script after syncing if needed for local development with Java 17"
